FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /normalizer ./cmd/normalizer

FROM alpine:latest
WORKDIR /
COPY --from=builder /normalizer /normalizer

EXPOSE 8081
CMD ["/normalizer"]